baseurl = "http://wizrd00.github.io"
title = "Arash"
theme = "coder"
languagecode = "en"
defaultcontentlanguage = "en"


[pagination]
pagerSize = 20

[markup.highlight]
style = "github-dark"

[params]
  author = "Arash Ghafari"
  info = "Network & System Programmer"
  description = "BrainDump"
  keywords = "blog,developer,programmer,personal"
  avatarurl = "images/avatar.png"

  since = 2026

  enableTwemoji = true

  colorScheme = "auto"
  hidecolorschemetoggle = false

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
  author = "authors"

# Social links
[[params.social]]
  name = "Github"
  icon = "fa-brands fa-github fa-2x"
  weight = 1
  url = "https://github.com/wizrd00/"
[[params.social]]
  name = "Telegram"
  icon = "fa-brands fa-telegram fa-2x"
  weight = 3
  url = "https://t.me/wizrd00/"

# Menu links
[[menu.main]]
  name = "Blog"
  weight = 1
  url  = "posts/"
[[menu.main]]
  name = "Projects"
  weight = 2
  url = "categories/projects/"
[[menu.main]]
  name = "About"
  weight = 3
  url = "about/"
